gcc: don't reset "public" flag in maybe_thunk_body()
This commit is a workaround for the internal compiler error (ICE):

 error: comdat-local function called by XYZ outside its comdat

The problem appears to affect unified destructors ("*D4Ev"), which are
put in a COMDAT section, then get cloned to D0Ev, D1Ev and D2Ev, all
of these calling the original D4Ev.  The make_decl_one_only() function
made these "public", which however gets reverted on D4Ev by
maybe_thunk_body().  However, only public functions are allowed to be
called from another COMDAT, which leads to the ICE (and crashes gcc).

So this workaround avoids resetting the "public" flag on D4Ev,
allowing D4Ev to be called from different COMDAT sections.

Refer to https://github.com/MaxKellermann/gcc/commit/935ab7c9d668fa3f6626a832093d60fb259ef643